
version: '3.4'

services:
  api-php:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api_symfony_php
    networks:
      - front
      - back

  api-nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api_symfony_nginx
    depends_on:
      - api-php
    ports: 
      - 8881:80
    volumes:
      - ./api/public:/srv/api/public:ro
    networks:
      - front
      - back

  # elk:
  #   image: willdurand/elk
  #   ports:
  #     - "8889:80"
  #   volumes:
  #     - ./elk/logstash:/etc/logstash:cached
  #     - ./elk/logstash/patterns:/opt/logstash/patterns:cached
  #     - ./logs/symfony:/var/www/symfony/var/log:cached
  #     - ./logs/nginx:/var/log/nginx:cached
  #   networks:
  #     - front
  #     - back

networks:
    front:
    back: